from enum import Enum


class State(str, Enum):
    # Section 1: Opening
    OPENING_GREETING = "OPENING_GREETING"
    CONFIRM_IDENTITY = "CONFIRM_IDENTITY"
    CHECK_AVAILABILITY = "CHECK_AVAILABILITY"
    CALLBACK_SCHEDULING = "CALLBACK_SCHEDULING"
    CAPTURE_CALLBACK_DATETIME = "CAPTURE_CALLBACK_DATETIME"
    FIRM_BUSINESS_CONFIRM = "FIRM_BUSINESS_CONFIRM"
    INVALID_REGISTRATION = "INVALID_REGISTRATION"
    EXPLAIN_PURPOSE = "EXPLAIN_PURPOSE"

    # Section 2: Billing Status
    ASK_BILLING_STATUS = "ASK_BILLING_STATUS"
    DELAY_REASON_PROBE = "DELAY_REASON_PROBE"
    WILL_NOT_USE_PROBE = "WILL_NOT_USE_PROBE"
    OFFER_SUPPORT_CALLBACK = "OFFER_SUPPORT_CALLBACK"
    RECORD_REASON_POLITE_CLOSE = "RECORD_REASON_POLITE_CLOSE"

    # Section 3: Details Verification
    DETAILS_VERIFICATION_INTRO = "DETAILS_VERIFICATION_INTRO"
    VERIFY_WHATSAPP = "VERIFY_WHATSAPP"
    COLLECT_ALTERNATE_NUMBER = "COLLECT_ALTERNATE_NUMBER"
    VERIFY_PINCODE = "VERIFY_PINCODE"
    VERIFY_BUSINESS_TRADE = "VERIFY_BUSINESS_TRADE"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    ASK_PRICE = "ASK_PRICE"

    # Section 4: Satisfaction
    SATISFACTION_CHECK = "SATISFACTION_CHECK"

    # Section 5: Support Guidance
    SUPPORT_GUIDANCE = "SUPPORT_GUIDANCE"
    EXPLAIN_MARG_HELP = "EXPLAIN_MARG_HELP"
    EXPLAIN_TICKET_SYSTEM = "EXPLAIN_TICKET_SYSTEM"
    CHECK_LICENSE_NUMBER = "CHECK_LICENSE_NUMBER"
    CAPTURE_ISSUE_CALLBACK = "CAPTURE_ISSUE_CALLBACK"
    HELPLINE_REMINDER = "HELPLINE_REMINDER"

    # Section 6: Issue / D-SAT
    ISSUE_HANDLING = "ISSUE_HANDLING"
    CAPTURE_ISSUE_SUMMARY = "CAPTURE_ISSUE_SUMMARY"
    DSAT_ESCALATION = "DSAT_ESCALATION"
    URGENT_ESCALATION_FLAG = "URGENT_ESCALATION_FLAG"
    CAPTURE_CALLBACK_TIME = "CAPTURE_CALLBACK_TIME"

    # Programmatic
    CHECK_SENTIMENT_ELIGIBILITY = "CHECK_SENTIMENT_ELIGIBILITY"

    # Section 8: Reference
    REFERENCE_PITCH = "REFERENCE_PITCH"
    CAPTURE_REFERENCE = "CAPTURE_REFERENCE"

    # Section 9: Closing
    WARM_CLOSING = "WARM_CLOSING"
    LOG_DISPOSITION = "LOG_DISPOSITION"
    END = "END"


# State type classification
AUTO_STATES = {
    State.OPENING_GREETING,
    State.EXPLAIN_PURPOSE,
    State.DETAILS_VERIFICATION_INTRO,
    State.URGENT_ESCALATION_FLAG,
    State.SUPPORT_GUIDANCE,
    State.EXPLAIN_MARG_HELP,
    State.HELPLINE_REMINDER,
    State.LOG_DISPOSITION,
}

TERMINAL_STATES = {
    State.INVALID_REGISTRATION,
    State.RECORD_REASON_POLITE_CLOSE,
    State.WARM_CLOSING,
}

PROGRAMMATIC_STATES = {
    State.CHECK_SENTIMENT_ELIGIBILITY,
}
