from enum import Enum


class State(str, Enum):
    OPENING_GREETING = "OPENING_GREETING"
    CONFIRM_IDENTITY = "CONFIRM_IDENTITY"
    CHECK_AVAILABILITY = "CHECK_AVAILABILITY"
    ASK_BILLING_STATUS = "ASK_BILLING_STATUS"

    VERIFY_WHATSAPP = "VERIFY_WHATSAPP"
    COLLECT_WHATSAPP_NUMBER = "COLLECT_WHATSAPP_NUMBER"
    ASK_ALTERNATE_NUMBER = "ASK_ALTERNATE_NUMBER"
    COLLECT_ALTERNATE_NUMBER = "COLLECT_ALTERNATE_NUMBER"
    VERIFY_PINCODE = "VERIFY_PINCODE"
    COLLECT_PINCODE = "COLLECT_PINCODE"
    VERIFY_BUSINESS_DETAILS = "VERIFY_BUSINESS_DETAILS"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    ASK_PURCHASE_AMOUNT = "ASK_PURCHASE_AMOUNT"

    SUPPORT_AND_REFERRAL = "SUPPORT_AND_REFERRAL"
    COLLECT_REFERRAL = "COLLECT_REFERRAL"

    CALLBACK_CLOSING = "CALLBACK_CLOSING"
    INVALID_REGISTRATION = "INVALID_REGISTRATION"
    WARM_CLOSING = "WARM_CLOSING"
    LOG_DISPOSITION = "LOG_DISPOSITION"
    END = "END"


AUTO_STATES = {
    State.CALLBACK_CLOSING,
    State.INVALID_REGISTRATION,
    State.WARM_CLOSING,
    State.LOG_DISPOSITION,
}

TERMINAL_STATES = {
    State.CALLBACK_CLOSING,
    State.INVALID_REGISTRATION,
    State.WARM_CLOSING,
}

PROGRAMMATIC_STATES: set[State] = set()
