from enum import Enum


class State(str, Enum):
    OPENING_GREETING = "OPENING_GREETING"
    CONFIRM_IDENTITY = "CONFIRM_IDENTITY"
    CHECK_AVAILABILITY = "CHECK_AVAILABILITY"
    ASK_WRONG_CONTACT_COMPANY = "ASK_WRONG_CONTACT_COMPANY"
    ASK_WRONG_CONTACT_TRADE = "ASK_WRONG_CONTACT_TRADE"
    ASK_WRONG_CONTACT_TYPE = "ASK_WRONG_CONTACT_TYPE"
    ASK_WRONG_CONTACT_NAME = "ASK_WRONG_CONTACT_NAME"
    ASK_CONCERNED_PERSON_CONTACT = "ASK_CONCERNED_PERSON_CONTACT"
    COLLECT_CONCERNED_PERSON_NUMBER = "COLLECT_CONCERNED_PERSON_NUMBER"
    CONFIRM_CONCERNED_PERSON_NUMBER = "CONFIRM_CONCERNED_PERSON_NUMBER"
    ASK_BILLING_STATUS = "ASK_BILLING_STATUS"
    EXPLORE_BILLING_BLOCKER = "EXPLORE_BILLING_BLOCKER"
    COLLECT_COMPLAINT_DETAIL = "COLLECT_COMPLAINT_DETAIL"
    ESCALATE_PAYMENT_DATE = "ESCALATE_PAYMENT_DATE"
    ESCALATE_PARTNER_NAME = "ESCALATE_PARTNER_NAME"
    ESCALATE_SWITCHED_SOFTWARE = "ESCALATE_SWITCHED_SOFTWARE"
    ESCALATE_SWITCH_REASON = "ESCALATE_SWITCH_REASON"
    ESCALATE_CLOSURE_REASON = "ESCALATE_CLOSURE_REASON"
    ESCALATE_TECHNICAL_ISSUE = "ESCALATE_TECHNICAL_ISSUE"
    COLLECT_TRAINING_PINCODE = "COLLECT_TRAINING_PINCODE"
    ASK_BILLING_START_TIMELINE = "ASK_BILLING_START_TIMELINE"
    DETOUR_ANYTHING_ELSE = "DETOUR_ANYTHING_ELSE"

    VERIFY_WHATSAPP = "VERIFY_WHATSAPP"
    COLLECT_WHATSAPP_NUMBER = "COLLECT_WHATSAPP_NUMBER"
    CONFIRM_WHATSAPP_NUMBER = "CONFIRM_WHATSAPP_NUMBER"
    ASK_ALTERNATE_NUMBER = "ASK_ALTERNATE_NUMBER"
    COLLECT_ALTERNATE_NUMBER = "COLLECT_ALTERNATE_NUMBER"
    CONFIRM_ALTERNATE_NUMBER = "CONFIRM_ALTERNATE_NUMBER"
    VERIFY_PINCODE = "VERIFY_PINCODE"
    COLLECT_PINCODE = "COLLECT_PINCODE"
    CONFIRM_PINCODE = "CONFIRM_PINCODE"
    VERIFY_BUSINESS_DETAILS = "VERIFY_BUSINESS_DETAILS"
    CONFIRM_BUSINESS_DETAILS = "CONFIRM_BUSINESS_DETAILS"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    COLLECT_EMAIL_CORRECTION = "COLLECT_EMAIL_CORRECTION"
    CONFIRM_EMAIL_CORRECTION = "CONFIRM_EMAIL_CORRECTION"
    ASK_PURCHASE_AMOUNT = "ASK_PURCHASE_AMOUNT"

    SUPPORT_AND_REFERRAL = "SUPPORT_AND_REFERRAL"
    COLLECT_REFERRAL_NAME = "COLLECT_REFERRAL_NAME"
    COLLECT_REFERRAL_NUMBER = "COLLECT_REFERRAL_NUMBER"
    CONFIRM_REFERRAL_NUMBER = "CONFIRM_REFERRAL_NUMBER"
    REFERRAL_DECLINE_NUDGE = "REFERRAL_DECLINE_NUDGE"
    ANSWER_USER_QUERY = "ANSWER_USER_QUERY"

    PRE_CLOSING = "PRE_CLOSING"
    BUSY_NUDGE = "BUSY_NUDGE"
    ASK_CALLBACK_TIME = "ASK_CALLBACK_TIME"
    CONFIRM_CALLBACK_TIME = "CONFIRM_CALLBACK_TIME"
    CALLBACK_CLOSING = "CALLBACK_CLOSING"
    INVALID_REGISTRATION = "INVALID_REGISTRATION"
    WARM_CLOSING = "WARM_CLOSING"
    FIXED_CLOSING = "FIXED_CLOSING"
    LOG_DISPOSITION = "LOG_DISPOSITION"
    END = "END"


AUTO_STATES = {
    State.PRE_CLOSING,
    State.CALLBACK_CLOSING,
    State.INVALID_REGISTRATION,
    State.WARM_CLOSING,
    State.FIXED_CLOSING,
    State.LOG_DISPOSITION,
}

TERMINAL_STATES = {
    State.FIXED_CLOSING,
}

PROGRAMMATIC_STATES: set[State] = set()
