from pathlib import Path

# Centralized constants for the Aakriti voice agent.

MAX_FALLBACKS_PER_STATE = 3
MAX_TOTAL_TRANSITIONS = 50
MAX_CALL_DURATION_SECONDS = 600
TRANSCRIPT_WINDOW_SIZE = 6
MAX_PRICE_ATTEMPTS = 2
SILENCE_TIMEOUT_SECONDS = 10
SILENCE_MAX_RETRIES = 2
CLASSIFIER_TIMEOUT_SECONDS = 2.25
LLM_TIMEOUT_SECONDS = 5.0
LLM_MAX_RETRIES = 1
AUTO_CALLBACK_RETRY_HOURS: tuple[int, int] = (24, 48)
CLASSIFIER_FASTPATH_MAX_CHARS = 40

TURN_DETECTION_MODE = "vad"
TURN_ENDPOINTING_MODE = "fixed"
TURN_ENDPOINTING_MIN_DELAY_SECONDS = 0.45
TURN_ENDPOINTING_MAX_DELAY_SECONDS = 1.8
TURN_INTERRUPTION_MODE = "vad"
TURN_INTERRUPTION_MIN_DURATION_SECONDS = 0.25
TURN_INTERRUPTION_MIN_WORDS = 0
TURN_FALSE_INTERRUPTION_TIMEOUT_SECONDS = 1.0
DISCARD_AUDIO_IF_UNINTERRUPTIBLE = False
PREEMPTIVE_GENERATION_ENABLED = False
MIN_CONSECUTIVE_SPEECH_DELAY_SECONDS = 0.0
AEC_WARMUP_DURATION_SECONDS = 1.0
TTS_TIMEOUT_SECONDS = 20.0
TTS_MAX_RETRIES = 2
TTS_RETRY_INTERVAL_SECONDS = 0.5
MEDIA_MAX_UNRECOVERABLE_ERRORS = 5
SARVAM_WS_HEARTBEAT_SECONDS = 10.0
SARVAM_REUSE_WS_CONNECTIONS = False

VALID_INTENTS = [
    "AFFIRM",
    "DENY",
    "INFORM",
    "REQUEST",
    "ASK",
    "OBJECT",
    "COMPLAIN",
    "ESCALATE",
    "DEFER",
    "ELABORATE",
    "GREET",
    "THANK",
    "GOODBYE",
    "OUT_OF_SCOPE",
    "UNCLEAR",
]

SYSTEM_PROMPT_FOR_CLASSIFIER = (
    "Classify the speech act of the given Hindi-English transcript. "
    "Output EXACTLY one label from: "
    "AFFIRM, DENY, INFORM, REQUEST, ASK, OBJECT, COMPLAIN, "
    "ESCALATE, DEFER, ELABORATE, GREET, THANK, GOODBYE, "
    "OUT_OF_SCOPE, UNCLEAR"
)

BASE_MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
_THIS_DIR = Path(__file__).resolve().parent
_PREFERRED_ADAPTER_DIR = _THIS_DIR / "models" / "आकृति-intent-classifier"
_LEGACY_ADAPTER_DIR = _THIS_DIR / "models" / "akash-intent-classifier"
ADAPTER_PATH = str(_PREFERRED_ADAPTER_DIR if _PREFERRED_ADAPTER_DIR.exists() else _LEGACY_ADAPTER_DIR)
